micronaut:
  server:
    port: 8081
  security:
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: ${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}
mongodb:
  package-names:
    - com.ideazlab.releaseninja
test-resources:
  containers:
    mongodb:
      image-name: mongo:latest
    redis:
      image-name: redis:6.2-alpine